# Generated by Django 2.1.3 on 2019-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=250)),
                ('livraison', models.CharField(max_length=250)),
                ('lunette', models.ImageField(upload_to='photos/achat')),
            ],
        ),
    ]
