# Generated by Django 2.1.3 on 2019-01-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='prenom',
        ),
    ]
