# Generated by Django 2.1.3 on 2019-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunette',
            name='image',
            field=models.ImageField(default='a.jpg', upload_to='photos/'),
        ),
    ]
