# Generated by Django 2.1.3 on 2019-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_lunette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunette',
            name='nature',
            field=models.CharField(choices=[('soleil', 'soleil'), ('vue', 'vue'), ('mode', 'mode'), ('classe', 'classe')], max_length=250),
        ),
    ]
