# Generated by Django 2.1.3 on 2019-01-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20190116_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunette',
            name='marque',
            field=models.CharField(choices=[('rayban', 'rayban'), ('quartier', 'quartier')], max_length=250),
        ),
    ]
