# Generated by Django 2.1.3 on 2019-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_auto_20190116_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='a.jpg', upload_to='photos/satisfaits')),
            ],
            options={
                'verbose_name': 'Satisfait',
            },
        ),
        migrations.AlterField(
            model_name='lunette',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
